using Core_API.Domain.Entities.Abstract;
using Core_API.Domain.Entities.Common;
using Core_API.Domain.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core_API.Domain.Entities
{
    /// <summary>
    /// Represents a single issued invoice sent to a customer.
    /// Extends <see cref="InvoiceHeaderBase"/> with invoice-specific lifecycle,
    /// payment tracking, and related collections.
    /// </summary>
    public class Invoice : InvoiceHeaderBase
    {
        // ── Identity ─────────────────────────────────────────────────────────

        /// <summary>
        /// Unique system-generated invoice number (e.g., "INV-2024-0001").
        /// </summary>
        [Required]
        [StringLength(50)]
        public string InvoiceNumber { get; set; }

        // ── Dates ─────────────────────────────────────────────────────────────

        /// <summary>
        /// Date the invoice was officially created and issued.
        /// </summary>
        [Required]
        public DateTime IssueDate { get; set; }

        /// <summary>
        /// Date by which payment is expected from the customer.
        /// </summary>
        public DateTime DueDate { get; set; }

        /// <summary>
        /// Date the invoice was delivered to the customer. Null if not yet sent.
        /// </summary>
        public DateTime? SentDate { get; set; } // When invoice was sent to customer

        /// <summary>
        /// Date the invoice was fully settled. Null if payment is still outstanding.
        /// </summary>
        public DateTime? PaidDate { get; set; } // When invoice was fully paid

        // ── Status ────────────────────────────────────────────────────────────

        /// <summary>
        /// Current lifecycle status of the invoice (e.g., Draft, Sent, Paid, Void).
        /// </summary>
        public InvoiceStatus InvoiceStatus { get; set; } = InvoiceStatus.Draft;

        /// <summary>
        /// Categorisation of the invoice (e.g., Standard, Recurring, CreditNote).
        /// </summary>
        public InvoiceType InvoiceType { get; set; } = InvoiceType.Standard;

        /// <summary>
        /// Current payment status reflecting how much has been collected (e.g., Pending, PartiallyPaid, Paid).
        /// </summary>
        public PaymentStatus PaymentStatus { get; set; } = PaymentStatus.Pending;

        // ── Financial Adjustments ─────────────────────────────────────────────

        /// <summary>
        /// Small rounding or manual adjustment applied to the invoice total.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal AdjustmentAmount { get; set; }

        /// <summary>
        /// Human-readable reason for the adjustment amount (e.g., "Rounding difference").
        /// </summary>
        [StringLength(200)]
        public string? AdjustmentDescription { get; set; }

        // ── Payment Summary ───────────────────────────────────────────────────

        /// <summary>
        /// Cumulative amount received against this invoice so far.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal AmountPaid { get; set; } // Total amount paid so far

        /// <summary>
        /// Outstanding balance still owed by the customer (TotalAmount − AmountPaid).
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal AmountDue { get; set; } // Remaining amount

        /// <summary>
        /// Total amount that has been refunded to the customer for this invoice.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal AmountRefunded { get; set; }

        // ── Payment Gateway ───────────────────────────────────────────────────
        /// <summary>
        /// Name of the payment gateway used (e.g., "Stripe", "Razorpay", "PayPal").
        /// </summary>
        [StringLength(50)]
        public string? PaymentGateway { get; set; }

        /// <summary>
        /// Unique transaction identifier returned by the payment gateway for reconciliation.
        /// </summary>
        [StringLength(500)]
        public string? PaymentTransactionId { get; set; }

        // ── Automation ────────────────────────────────────────────────────────
        /// <summary>
        /// Indicates whether this invoice was automatically generated by the system
        /// rather than created manually by a user.
        /// </summary>
        public bool IsAutomated { get; set; }

        // ── Recurring Reference ───────────────────────────────────────────────

        /// <summary>
        /// Foreign key to the parent <see cref="RecurringInvoice"/> template.
        /// Null when this is a standalone, one-time invoice.
        /// </summary>
        public int? RecurringInvoiceId { get; set; }

        /// <summary>
        /// Navigation property to the recurring template that generated this invoice.
        /// </summary>
        [ForeignKey("RecurringInvoiceId")]
        public RecurringInvoice? RecurringInvoice { get; set; }

        /// <summary>
        /// Returns true when the invoice originates from or belongs to a recurring schedule.
        /// Computed; not persisted to the database.
        /// </summary>
        [NotMapped]
        public bool IsRecurring => InvoiceType == InvoiceType.Recurring || RecurringInvoiceId.HasValue;

        // ── Source / Integration ──────────────────────────────────────────────

        /// <summary>
        /// Identifies the originating system or channel (e.g., "API", "Manual", "Import").
        /// </summary>
        [StringLength(200)]
        public string? SourceSystem { get; set; }

        // ── Collections ───────────────────────────────────────────────────────

        /// <summary>Line items detailing goods or services billed on this invoice.</summary>
        public List<InvoiceItem> InvoiceItems { get; set; } = new();

        /// <summary>Breakdown of taxes applied to this invoice.</summary>
        public List<InvoiceTaxDetail> TaxDetails { get; set; } = new();

        /// <summary>Discounts applied at the invoice level.</summary>
        public List<InvoiceDiscount> Discounts { get; set; } = new();

        /// <summary>Files or documents attached to this invoice (e.g., supporting PDFs).</summary>
        public List<InvoiceAttachment> InvoiceAttachments { get; set; } = new();

        /// <summary>History of all payment transactions recorded against this invoice.</summary>
        public List<InvoicePayment> Payments { get; set; } = new();

        /// <summary>Full audit trail of every status change and action taken on this invoice.</summary>
        public List<InvoiceAuditLog> AuditLogs { get; set; } = new();
    }

    /// <summary>
    /// Represents a single line item on an invoice, extending the shared
    /// <see cref="LineItemBase"/> with invoice-specific tax and gross totals.
    /// </summary>
    public class InvoiceItem : LineItemBase
    {
        /// <summary>
        /// Foreign key linking this line item to its parent invoice.
        /// </summary>
        [Required]
        public int InvoiceId { get; set; }

        /// <summary>
        /// Navigation property to the parent <see cref="Invoice"/>.
        /// </summary>
        [ForeignKey("InvoiceId")]
        public Invoice Invoice { get; set; }

        /// <summary>
        /// Tax amount calculated for this specific line item.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal TaxAmount { get; set; }

        /// <summary>
        /// Gross amount for this line item inclusive of tax (UnitPrice × Quantity + TaxAmount).
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal TotalAmount { get; set; } 
    }

    /// <summary>
    /// Stores the tax breakdown for a specific tax applied to an invoice,
    /// extending <see cref="TaxDetailBase"/> with the invoice foreign key.
    /// </summary>
    public class InvoiceTaxDetail : TaxDetailBase
    {
        /// <summary>
        /// Foreign key linking this tax detail to its parent invoice.
        /// </summary>
        [Required]
        public int InvoiceId { get; set; }

        /// <summary>
        /// Navigation property to the parent <see cref="Invoice"/>.
        /// </summary>
        [ForeignKey("InvoiceId")]
        public Invoice? Invoice { get; set; }
    }

    /// <summary>
    /// Represents a discount applied at the invoice level,
    /// extending <see cref="DiscountBase"/> with the invoice foreign key.
    /// </summary>
    public class InvoiceDiscount : DiscountBase
    {
        /// <summary>
        /// Foreign key linking this discount to its parent invoice.
        /// </summary>
        [Required]
        public int InvoiceId { get; set; }

        /// <summary>
        /// Navigation property to the parent <see cref="Invoice"/>.
        /// </summary>
        [ForeignKey("InvoiceId")]
        public Invoice Invoice { get; set; }
    }

    /// <summary>
    /// Records a single payment transaction received against an invoice.
    /// Multiple payments are allowed to support partial and instalment payments.
    /// </summary>
    public class InvoicePayment : BaseEntity
    {
        // ── Invoice Reference ─────────────────────────────────────────────────

        /// <summary>
        /// Foreign key to the invoice this payment is applied against.
        /// </summary>
        [Required]
        public int InvoiceId { get; set; }

        /// <summary>
        /// Navigation property to the parent <see cref="Invoice"/>.
        /// </summary>
        [ForeignKey("InvoiceId")]
        public Invoice Invoice { get; set; }

        // ── Payment Details ───────────────────────────────────────────────────

        /// <summary>
        /// Date and time the payment was received or processed.
        /// </summary>
        [Required]
        public DateTime PaymentDate { get; set; }

        /// <summary>
        /// Monetary value of this payment transaction.
        /// </summary>
        [Required]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; }

        /// <summary>
        /// Method used to make the payment (e.g., "Credit Card", "Bank Transfer", "Cash", "Check").
        /// </summary>
        [Required]
        [StringLength(50)]
        public string PaymentMethod { get; set; }

        /// <summary>
        /// External reference for this payment such as a transaction ID or cheque number.
        /// </summary>
        [StringLength(100)]
        public string PaymentReference { get; set; }

        /// <summary>
        /// Processing status of this payment record (e.g., "Pending", "Completed", "Failed").
        /// </summary>
        [StringLength(50)]
        public string PaymentStatus { get; set; }

        // ── Bank & Refund ─────────────────────────────────────────────────────

        /// <summary>
        /// Identifier of the bank account into which this payment was deposited. Null if not applicable.
        /// </summary>
        public int? BankAccountId { get; set; }

        /// <summary>
        /// Indicates whether this record represents a refund issued to the customer
        /// rather than a payment received.
        /// </summary>
        public bool IsRefund { get; set; }
    }

    /// <summary>
    /// Immutable audit log entry recording every significant action
    /// performed on an invoice for compliance and traceability.
    /// </summary>
    public class InvoiceAuditLog : BaseEntity
    {
        // ── Invoice Reference ─────────────────────────────────────────────────

        /// <summary>
        /// Foreign key to the invoice this log entry belongs to.
        /// </summary>
        [Required]
        public int InvoiceId { get; set; }

        /// <summary>
        /// Navigation property to the parent <see cref="Invoice"/>.
        /// </summary>
        [ForeignKey("InvoiceId")]
        public Invoice Invoice { get; set; }

        // ── Log Details ───────────────────────────────────────────────────────

        /// <summary>
        /// Short label for the action performed (e.g., "Created", "Sent", "Paid", "Voided").
        /// </summary>
        [Required]
        [StringLength(50)]
        public string Action { get; set; }

        /// <summary>
        /// Human-readable description of what happened and why.
        /// </summary>
        [Required]
        [StringLength(500)]
        public string Description { get; set; }

        /// <summary>
        /// JSON-serialised snapshot of field-level changes made during this action.
        /// </summary>
        [StringLength(2000)]
        public string Changes { get; set; }

        // ── Request Context ───────────────────────────────────────────────────

        /// <summary>
        /// IP address of the client that triggered this action, for security auditing.
        /// </summary>
        public string IpAddress { get; set; }

        /// <summary>
        /// User-agent string of the client browser or API consumer.
        /// </summary>
        public string UserAgent { get; set; }
    }

    /// <summary>
    /// Represents a file attached to an invoice, such as a supporting document,
    /// signed copy, or proof of delivery.
    /// </summary>
    public class InvoiceAttachment : BaseEntity
    {
        // ── Invoice Reference ─────────────────────────────────────────────────
        /// <summary>
        /// Foreign key to the invoice this attachment belongs to.
        /// </summary>
        public int InvoiceId { get; set; }

        /// <summary>
        /// Navigation property to the parent <see cref="Invoice"/>.
        /// </summary>
        [ForeignKey("InvoiceId")]
        public Invoice Invoice { get; set; }

        // ── File Identity ─────────────────────────────────────────────────────

        /// <summary>
        /// Original name of the uploaded file including extension (e.g., "invoice_signed.pdf").
        /// </summary>
        [Required]
        [StringLength(255)]
        public string FileName { get; set; }

        /// <summary>
        /// Server-side file system path where the file is stored.
        /// </summary>
        [StringLength(1000)]
        public string? FilePath { get; set; }

        /// <summary>
        /// Publicly accessible URL for cloud-hosted files (e.g., S3, Azure Blob). Null for local storage.
        /// </summary>
        [StringLength(500)]
        public string? FileUrl { get; set; }

        // ── File Metadata ─────────────────────────────────────────────────────

        /// <summary>
        /// MIME type of the file (e.g., "application/pdf", "image/png").
        /// </summary>
        [StringLength(100)]
        public string? ContentType { get; set; }

        /// <summary>
        /// Size of the file in bytes.
        /// </summary>
        [Required]
        public long FileSize { get; set; }

        /// <summary>
        /// Optional description or label for the attachment (e.g., "Signed Invoice Copy").
        /// </summary>
        [StringLength(500)]
        public string? Description { get; set; }

        // ── Visibility ────────────────────────────────────────────────────────

        /// <summary>
        /// Controls whether the customer can view this attachment via the customer portal.
        /// Defaults to <c>true</c>.
        /// </summary>
        public bool IsPublic { get; set; } = true;

    }
}