using Core_API.Domain.Entities.Abstract;
using Core_API.Domain.Entities.Common;
using Core_API.Domain.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core_API.Domain.Entities
{

    /// <summary>
    /// Defines a recurring invoice template that automatically generates
    /// <see cref="Invoice"/> instances on a configurable schedule.
    /// Extends <see cref="InvoiceHeaderBase"/> with scheduling, automation,
    /// and template-override settings.
    /// </summary>
    public class RecurringInvoice : InvoiceHeaderBase
    {
        // ── Identity ──────────────────────────────────────────────────────────

        /// <summary>
        /// Display name for this recurring template (e.g., "Monthly Retainer – Acme Corp").
        /// </summary>
        [Required]
        [StringLength(200)]
        public string Name { get; set; }

        /// <summary>
        /// Optional description providing context about the purpose of this recurring schedule.
        /// </summary>
        [StringLength(1000)]
        public string Description { get; set; }

        // ── Frequency & Interval ──────────────────────────────────────────────

        /// <summary>
        /// Base recurrence unit (e.g., Daily, Weekly, Monthly, Annually).
        /// </summary>
        [Required]
        public RecurringFrequency Frequency { get; set; }

        /// <summary>
        /// Multiplier applied to <see cref="Frequency"/> (e.g., 2 with Weekly = every 2 weeks).
        /// Must be between 1 and 365.
        /// </summary>
        [Required]
        [Range(1, 365)]
        public int FrequencyInterval { get; set; } = 1;

        // ── Schedule Specifics ────────────────────────────────────────────────

        /// <summary>
        /// Day of the month (1–31) on which the invoice is generated. Used for monthly schedules.
        /// </summary>
        public int? DayOfMonth { get; set; }

        /// <summary>
        /// Day of the week on which the invoice is generated. Used for weekly schedules.
        /// </summary>
        public DayOfWeek? DayOfWeek { get; set; }

        /// <summary>
        /// Ordinal week of the month (1 = First, 2 = Second … 5 = Last).
        /// Used for "first Monday of the month" style schedules.
        /// </summary>
        public int? WeekOfMonth { get; set; }

        /// <summary>
        /// Month of the year (1–12) on which the invoice is generated. Used for annual schedules.
        /// </summary>
        public int? MonthOfYear { get; set; }

        // ── Lifecycle Dates ───────────────────────────────────────────────────

        /// <summary>
        /// Date from which the recurring schedule becomes active and starts generating invoices.
        /// </summary>
        [Required]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// Date after which no further invoices are generated. Null means the schedule runs indefinitely.
        /// </summary>
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// Date and time when this schedule was paused. Null if currently active.
        /// </summary>
        public DateTime? PausedDate { get; set; }

        /// <summary>
        /// Date and time when this schedule was permanently cancelled. Null if not cancelled.
        /// </summary>
        public DateTime? CancelledDate { get; set; }

        // ── Occurrence Tracking ───────────────────────────────────────────────

        /// <summary>
        /// Maximum number of invoices to generate before automatically completing the schedule.
        /// Null means unlimited occurrences.
        /// </summary>
        public int? MaxOccurrences { get; set; }

        /// <summary>
        /// Running count of invoices successfully generated by this schedule.
        /// </summary>
        public int OccurrencesGenerated { get; set; } = 0;

        /// <summary>
        /// Date on which the next invoice instance is scheduled to be generated.
        /// </summary>
        [Required]
        public DateTime NextInvoiceDate { get; set; }

        /// <summary>
        /// Date on which the most recent invoice was generated. Null before the first run.
        /// </summary>
        public DateTime? LastInvoiceDate { get; set; }

        // ── Status ────────────────────────────────────────────────────────────

        /// <summary>
        /// Current operational status of this recurring template
        /// (e.g., Draft, Active, Paused, Completed, Cancelled, Expired).
        /// </summary>
        [Required]
        public RecurringInvoiceStatus Status { get; set; } = RecurringInvoiceStatus.Draft;

        // ── Generation Settings ───────────────────────────────────────────────

        /// <summary>
        /// Number of days before the due date that the invoice should be pre-generated.
        /// 0 means generate on the due date itself.
        /// </summary>
        public int GenerateInAdvanceDays { get; set; } = 0;

        // ── Automation Flags ──────────────────────────────────────────────────

        /// <summary>
        /// When true, generated invoices are automatically sent to the customer without manual intervention.
        /// </summary>
        public bool AutoSend { get; set; } = false;

        /// <summary>
        /// When true, an email notification is sent to the customer each time an invoice is generated.
        /// </summary>
        public bool AutoEmail { get; set; } = false;

        /// <summary>
        /// When true, the customer's saved payment method is automatically charged on the due date.
        /// </summary>
        public bool AutoCharge { get; set; } = false;

        /// <summary>
        /// When true, a payment reminder email is sent to the customer a set number of days before the due date.
        /// </summary>
        public bool ReminderBeforeDue { get; set; } = false;

        /// <summary>
        /// Number of days before the due date to send the payment reminder. Only used when
        /// <see cref="ReminderBeforeDue"/> is true.
        /// </summary>
        public int ReminderDaysBefore { get; set; } = 3;

        // ── Source Template ───────────────────────────────────────────────────

        /// <summary>
        /// Foreign key to the original <see cref="Invoice"/> used as the template
        /// for generating recurring instances. Null if built from scratch.
        /// </summary>
        public int? SourceInvoiceId { get; set; }

        /// <summary>
        /// Navigation property to the source invoice template.
        /// </summary>
        [ForeignKey("SourceInvoiceId")]
        public Invoice SourceInvoice { get; set; }

        // ── Template Overrides ────────────────────────────────────────────────
        // Optional fields that override values from the source invoice on each generated instance.

        /// <summary>
        /// Overrides the purchase order number on generated invoices.
        /// </summary>
        [StringLength(50)]
        public string? OverridePONumber { get; set; }

        /// <summary>
        /// Overrides the customer-facing notes on generated invoices.
        /// </summary>
        [StringLength(1000)]
        public string? OverrideCustomerNotes { get; set; }

        /// <summary>
        /// Overrides the terms and conditions text on generated invoices.
        /// </summary>
        [StringLength(500)]
        public string? OverrideTermsAndConditions { get; set; }

        /// <summary>
        /// Overrides the footer note displayed on generated invoices.
        /// </summary>
        [StringLength(500)]
        public string? OverrideFooterNote { get; set; }

        /// <summary>
        /// Overrides the project detail field on generated invoices.
        /// </summary>
        [StringLength(200)]
        public string? OverrideProjectDetail { get; set; }

        /// <summary>
        /// Overrides the payment method specified on generated invoices.
        /// </summary>
        [StringLength(100)]
        public string? OverridePaymentMethod { get; set; }

        /// <summary>
        /// Overrides the payment terms (in days) on generated invoices (e.g., 30 for "Net 30").
        /// </summary>
        public int? OverridePaymentTerms { get; set; }

        /// <summary>
        /// Overrides the shipping amount on generated invoices.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal? OverrideShippingAmount { get; set; }

        /// <summary>
        /// Overrides the adjustment/rounding amount on generated invoices.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal? OverrideAdjustmentAmount { get; set; }

        /// <summary>
        /// Overrides the description for the adjustment amount on generated invoices.
        /// </summary>
        [StringLength(200)]
        public string? OverrideAdjustmentDescription { get; set; }

        // ── Collections ───────────────────────────────────────────────────────

        /// <summary>
        /// All invoice instances generated by this recurring schedule,
        /// linking each run to its produced <see cref="Invoice"/>.
        /// </summary>
        public List<RecurringInvoiceInstance> GeneratedInvoices { get; set; } = new();

        /// <summary>
        /// Full audit trail of every change and action taken on this recurring template.
        /// </summary>
        public List<RecurringInvoiceAuditLog> AuditLogs { get; set; } = new();
    }

    /// <summary>
    /// Tracks a single generation event — the link between a
    /// <see cref="RecurringInvoice"/> template and the <see cref="Invoice"/>
    /// it produced on a particular run.
    /// </summary>
    public class RecurringInvoiceInstance : BaseEntity
    {
        // ── References ────────────────────────────────────────────────────────

        /// <summary>
        /// Foreign key to the parent recurring template that triggered this generation.
        /// </summary>
        [Required]
        public int RecurringInvoiceId { get; set; }

        /// <summary>
        /// Navigation property to the parent <see cref="RecurringInvoice"/> template.
        /// </summary>
        [ForeignKey("RecurringInvoiceId")]
        public RecurringInvoice RecurringInvoice { get; set; }

        /// <summary>
        /// Foreign key to the <see cref="Invoice"/> produced during this generation run.
        /// </summary>
        [Required]
        public int InvoiceId { get; set; }

        /// <summary>
        /// Navigation property to the generated <see cref="Invoice"/>.
        /// </summary>
        [ForeignKey("InvoiceId")]
        public Invoice Invoice { get; set; }

        // ── Generation Details ────────────────────────────────────────────────

        /// <summary>
        /// Actual date and time the invoice was generated.
        /// </summary>
        [Required]
        public DateTime GeneratedDate { get; set; }

        /// <summary>
        /// The date on which generation was originally scheduled, before any delays or retries.
        /// </summary>
        public DateTime ScheduledGenerationDate { get; set; }

        /// <summary>
        /// One-based counter indicating which occurrence in the series this instance represents.
        /// </summary>
        public int SequenceNumber { get; set; }

        /// <summary>
        /// Invoice number assigned to the generated invoice (e.g., "INV-2024-0042").
        /// </summary>
        [Required]
        [StringLength(50)]
        public string GeneratedInvoiceNumber { get; set; }

        /// <summary>
        /// Total monetary amount of the generated invoice.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; }

        /// <summary>
        /// Optional notes recorded at the time of generation (e.g., manual overrides applied).
        /// </summary>
        [StringLength(500)]
        public string? Notes { get; set; }

        // ── Generation Status ─────────────────────────────────────────────────

        /// <summary>
        /// Outcome of the generation attempt (Success, Failed, RetryPending, Skipped).
        /// </summary>
        public GenerationStatus GenerationStatus { get; set; } = GenerationStatus.Success;

        /// <summary>
        /// Descriptive error message captured when <see cref="GenerationStatus"/> is Failed.
        /// Null on successful runs.
        /// </summary>
        public string? ErrorMessage { get; set; }

        /// <summary>
        /// Number of times generation has been retried after an initial failure.
        /// </summary>
        public int RetryCount { get; set; } = 0;
    }

    /// <summary>
    /// Immutable audit log entry for a recurring invoice template,
    /// recording every configuration change or lifecycle event
    /// for compliance and traceability.
    /// </summary>
    public class RecurringInvoiceAuditLog : AuditLogBase
    {
        /// <summary>
        /// Foreign key to the recurring invoice template this log entry belongs to.
        /// </summary>
        [Required]
        public int RecurringInvoiceId { get; set; }

        /// <summary>
        /// Navigation property to the parent <see cref="RecurringInvoice"/> template.
        /// </summary>
        [ForeignKey("RecurringInvoiceId")]
        public RecurringInvoice RecurringInvoice { get; set; }
    }
}