using Core_API.Domain.Abstractions;
using Core_API.Domain.Common;
using Core_API.Domain.Entities.RecurringInvoices;
using Core_API.Domain.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core_API.Domain.Entities.Invoices
{
    /// <summary>
    /// Represents a single issued invoice sent to a customer.
    /// Extends <see cref="InvoiceHeaderBase"/> with invoice-specific lifecycle,
    /// payment tracking, and related collections.
    /// </summary>
    public class Invoice : InvoiceHeaderBase
    {
        // ── Identity ─────────────────────────────────────────────────────────

        /// <summary>
        /// Unique system-generated invoice number (e.g., "INV-2024-0001").
        /// </summary>
        [Required]
        [StringLength(50)]
        public string InvoiceNumber { get; set; }

        // ── Dates ─────────────────────────────────────────────────────────────

        /// <summary>
        /// Date the invoice was officially created and issued.
        /// </summary>
        [Required]
        public DateTime IssueDate { get; set; }

        /// <summary>
        /// Date by which payment is expected from the customer.
        /// </summary>
        public DateTime DueDate { get; set; }

        /// <summary>
        /// Date the invoice was delivered to the customer. Null if not yet sent.
        /// </summary>
        public DateTime? SentDate { get; set; } // When invoice was sent to customer

        /// <summary>
        /// Date the invoice was fully settled. Null if payment is still outstanding.
        /// </summary>
        public DateTime? PaidDate { get; set; } // When invoice was fully paid

        // ── Status ────────────────────────────────────────────────────────────

        /// <summary>
        /// Current lifecycle status of the invoice (e.g., Draft, Sent, Paid, Void).
        /// </summary>
        public InvoiceStatus InvoiceStatus { get; set; } = InvoiceStatus.Draft;

        /// <summary>
        /// Categorisation of the invoice (e.g., Standard, Recurring, CreditNote).
        /// </summary>
        public InvoiceType InvoiceType { get; set; } = InvoiceType.Standard;

        /// <summary>
        /// Current payment status reflecting how much has been collected (e.g., Pending, PartiallyPaid, Paid).
        /// </summary>
        public PaymentStatus PaymentStatus { get; set; } = PaymentStatus.Pending;

        // ── Financial Adjustments ─────────────────────────────────────────────

        /// <summary>
        /// Small rounding or manual adjustment applied to the invoice total.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal AdjustmentAmount { get; set; }

        /// <summary>
        /// Human-readable reason for the adjustment amount (e.g., "Rounding difference").
        /// </summary>
        [StringLength(200)]
        public string? AdjustmentDescription { get; set; }

        // ── Payment Summary ───────────────────────────────────────────────────

        /// <summary>
        /// Cumulative amount received against this invoice so far.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal AmountPaid { get; set; } // Total amount paid so far

        /// <summary>
        /// Outstanding balance still owed by the customer (TotalAmount − AmountPaid).
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal AmountDue { get; set; } // Remaining amount

        /// <summary>
        /// Total amount that has been refunded to the customer for this invoice.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal AmountRefunded { get; set; }

        // ── Payment Gateway ───────────────────────────────────────────────────
        /// <summary>
        /// Name of the payment gateway used (e.g., "Stripe", "Razorpay", "PayPal").
        /// </summary>
        [StringLength(50)]
        public string? PaymentGateway { get; set; }

        /// <summary>
        /// Unique transaction identifier returned by the payment gateway for reconciliation.
        /// </summary>
        [StringLength(500)]
        public string? PaymentTransactionId { get; set; }

        // ── Automation ────────────────────────────────────────────────────────
        /// <summary>
        /// Indicates whether this invoice was automatically generated by the system
        /// rather than created manually by a user.
        /// </summary>
        public bool IsAutomated { get; set; }

        // ── Recurring Reference ───────────────────────────────────────────────

        /// <summary>
        /// Foreign key to the parent <see cref="RecurringInvoice"/> template.
        /// Null when this is a standalone, one-time invoice.
        /// </summary>
        public int? RecurringInvoiceId { get; set; }

        /// <summary>
        /// Navigation property to the recurring template that generated this invoice.
        /// </summary>
        [ForeignKey("RecurringInvoiceId")]
        public RecurringInvoice? RecurringInvoice { get; set; }

        /// <summary>
        /// Returns true when the invoice originates from or belongs to a recurring schedule.
        /// Computed; not persisted to the database.
        /// </summary>
        [NotMapped]
        public bool IsRecurring => InvoiceType == InvoiceType.Recurring || RecurringInvoiceId.HasValue;

        // ── Source / Integration ──────────────────────────────────────────────

        /// <summary>
        /// Identifies the originating system or channel (e.g., "API", "Manual", "Import").
        /// </summary>
        [StringLength(200)]
        public string? SourceSystem { get; set; }

        // ── Collections ───────────────────────────────────────────────────────

        /// <summary>Line items detailing goods or services billed on this invoice.</summary>
        public List<InvoiceItem> InvoiceItems { get; set; } = new();

        /// <summary>Breakdown of taxes applied to this invoice.</summary>
        public List<InvoiceTaxDetail> TaxDetails { get; set; } = new();

        /// <summary>Discounts applied at the invoice level.</summary>
        public List<InvoiceDiscount> Discounts { get; set; } = new();

        /// <summary>Files or documents attached to this invoice (e.g., supporting PDFs).</summary>
        public List<InvoiceAttachment> InvoiceAttachments { get; set; } = new();

        /// <summary>History of all payment transactions recorded against this invoice.</summary>
        public List<InvoicePayment> Payments { get; set; } = new();

        /// <summary>Full audit trail of every status change and action taken on this invoice.</summary>
        public List<InvoiceAuditLog> AuditLogs { get; set; } = new();
    }
}